[project]
name = "lesson-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.6.2",
    "celery-types>=0.24.0",
    "django>=6.0.1",
    "python-dotenv>=1.2.1",
]
